[package]
name = "webapp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.66" }

log = "0.4.11"
wasm-logger = "0.2.0"
console_error_panic_hook = { version = "0.1.5" }
